# Site
repository: r-bit-rry/r-bit-rry.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Roy Belio
title: Senior Software Engineer
email: royfbelio@gmail.com
website: https://github.com/r-bit-rry

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  r-bit-rry
stackoverflow_username: "2250010"
linkedin_username: roy-belio


# About Section
about_title: WHOAMI
about_profile_image: images/profile.jpg
about_content: |
  Enthusiast, <mark>Linux</mark> first, software engineer, with over 10 years of experience, ready to passionately tackle any challenge that can be solved with a piece of code.
  
  I am most skilled in: <mark>C#/.NET</mark>, <mark>Python</mark> and <mark>Rust</mark> and Cross Platform Development

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Microsoft
        link: www.microsoft.com
        sub_title: Software Developer Engineer II @ MSEC
        caption: May 2020 - Present
        description: |
          **<mark>Rust</mark>-based client in cross-platform domain:**
            - Co-led the design, development, and deployment of Microsoft's first cross-platform <mark>Rust</mark> client.
            - Introduced <mark>Rust</mark> to Windows OS and ensured <mark>MacOS</mark> and <mark>Linux</mark> compliance, achieving Microsoft-signed product status.

          **Domain leader in <mark>Microsoft Defender for Endpoint</mark> vulnerability management:**
            - Led the development of Threat Vulnerability Management's various endpoint clients.
            - Spearheaded the development of various scrapers/spiders for vulnerability feed collection.
            - Led <mark>Hardware</mark> and <mark>Firmware</mark> detection research and design across all platforms (Windows, Linux, MacOS) using <mark>C++</mark>, <mark>.NET</mark>, and <mark>Rust</mark>.
            - Managed the normalization service, maintaining high KPIs through <mark>CVE</mark> and <mark>CPE</mark> uniform naming.

          **Innovation in Solution Development:**
            - Designed and patented an alternative network protocol for data sync, saving Microsoft millions annually.
            - Developed a Windows kernel and NTFS-based solution for efficient scanning (using <mark>MFT</mark>) and metadata collection from files of interest.

          **Key Contributions to <mark>Microsoft Defender for Containers</mark> Vulnerability Management:**
            - Deployed <mark>Rust</mark>-based binary, scrapers, and backend logic for comparison with Qualys.
            - Enhanced support for developer package vulnerabilities, integrating <mark>GitHub Advisory</mark> vulnerabilities DB.
            - Contributed <mark>Docker</mark> and <mark>Azure</mark> Container Registry specific code for layer and image analysis.

          **Addressing High Profile Vulnerabilities like <mark>log4j</mark>:**
            - Provided critical code and expertise for accurate Java software detection.
            - Designed and developed detection and collection systems for various Developer Packages (<mark>Python</mark>, <mark>npm</mark>, <mark>NuGet</mark>, <mark>Java</mark>, <mark>Go</mark>).
            - Led browser-extension collection and analysis.

          **Software Engineering Expertise:**
            - Proficient in implementing and refactoring complex codebases.
            - Rapidly masters new technologies.
            - Strong foundation in <mark>C#</mark>, <mark>Rust</mark>, and <mark>Python</mark> development with a commitment to continuous learning.

      - layout: left
        border: weak
        title: INFINIDAT
        link: www.infinidat.com
        sub_title: Senior Python Developer @ Big Data Team
        caption: November 2017 - May 2020
        description: |
          **Large-Scale Product Development:**
          - Developed products to collect, parse, aggregate, mutate, and expose data from deployed Infinidat systems for customer and internal use

          **Python Distributions:**
          - Created relocatable <mark>Python</mark> distributions for open-source use across multiple platforms and architectures

          **Code Migration:**
          - Spearheaded code migration for multiple projects from <mark>Python 2</mark> to <mark>Python 3</mark>

      - layout: left
        title: Check Point Software Technologies
        link: www.checkpoint.com
        sub_title: Software Engineer
        caption: Auguest 2014 - November 2017
        description: |
          **Security Analyst:**
            - Analyzed network traffic and identified data patterns using <mark>Wireshark</mark> and <mark>tcpdump</mark>.
            - Mastered <mark>Regular Expressions</mark> for pattern recognition.

          **Software Developer:**
            - Created a reverse engineering solution for malicious traffic detection using <mark>Python</mark> and <mark>C/C++</mark>.
            - Developed big-data tools for network protocol profiling.
            - Built automation infrastructure for web-platform services.

          **Full Stack Developer:**
            - Developed server-side API code using <mark>Java</mark>, <mark>Spring Framework</mark>, and <mark>Spring-Security</mark>.
            - Worked on front-end development with <mark>AngularJS</mark>.
            - Conducted comprehensive testing with <mark>Grunt</mark>, <mark>Protractor</mark>, and <mark>Selenium</mark>.

          **Software Developer (Telecom Team):**
            - Developed secure server-side API for large Telecom corporations using <mark>PHP5</mark>/<mark>Postgresql</mark>/<mark>Apache</mark> stack.
            - Conducted testing with <mark>Junit</mark> and managed product lifecycle with <mark>Jenkins</mark> Pipelines.
            - Developed server-side components with <mark>Python</mark> and managed deployment with <mark>Puppet</mark>.
            - Orchestrated <mark>Postgresql</mark> clustering and replication for failsafe operation.

          **Product Development:**
            - Contributed to product development across multiple distributed virtualized platforms, including <mark>Gaia</mark> (Checkpoint Proprietary OS), <mark>Windows Server</mark>, and <mark>RHEL</mark>.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Technion - Israel Institute of Technology
        caption: 2011 - 2016
        sub_title: Industrial Engineering - Business Information systems
        quote: >
          Established in 1912 in Haifa, Israel, is the country's oldest university and a pivotal force in the fields of science and engineering
        description: |
          During my time at The Technion I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about latest technologies used in the industry.

  - title: Contributions
    layout: list
    content:
      - layout: top-middle
        title: Patent
        sub_title: UPDATING A STATE OF A CLIENT DEVICE USING A LIMITED EVENT SIZE PROTOCOL
        caption: 411583-US-NP · Filed May 26, 2022
      
      - layout: top-middle
        title: Final Project
        sub_title: Gamification of Goal Recognition Design Problems
        caption: March 2016
        description: |
          Designing and implementing of Goal Recognition Design game to show the benefits of such algorithms. The GRD is an A.I problem set, algorithms that solve this problem set do so by reshaping the problems topology in order optimize Goal Recognition algorithms performance.
          Developed with <mark>Java</mark>, <mark>JavaFX</mark>, and <mark>Android</mark>.
      
      - layout: top-middle
        title: Voluneteering
        sub_title: SII-the standards institution of israel Central Committee Member
        caption: August 2020 - Present
        description: |
         - Member of the Central Comitee for Technology and Information.
         - Member of the Cyber Comitee.
         - Member of Biometrics Commitee.

  - title: All work and no fun makes Roy a dull boy
    layout: text
    content: |
      Alongside my interests in cyber security and software engineering some of my other interests and hobbies are:
      - Mountaineering and Hiking
      - Playing classical music on the guitar
      - Bachata Dancing
      - Bouldering
      - Boxing
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
