# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Roy Belio
title: Senior Software Engineer
email: royfbelio@gmail.com
website: https://github.com/r-bit-rry

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  r-bit-rry
stackoverflow_username: "2250010"
linkedin_username: roy-belio


# About Section
about_title: WHOAMI
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Enthusiast senior software engineer, with over 10 years of experience, ready to passionately tackle any challenge that can be solved with a piece of code.

  I am most skilled in: <mark>C#/Dotnet</mark>, <mark>Python</mark> and <mark>Rust</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        link: www.microsoft.com
        # link_text: boringcompany.com
        sub_title: Software Developer Engineer II @ MSEC
        caption: May 2020 - Present
        quote: >
          "Tackling the puzzles of the 21st century by digging holes so deep we're expecting to find dinosaur fossils, and whipping up solutions so revolutionary, they make *Microsoft Defender for Enterprise* look like a rubber duck in a tech pond."
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Infinidat
        link: www.infinidat.com
        # link_text: boringcompany.com
        sub_title: Senior Python Developer @ Big Data Team
        caption: November 2017 - May 2020
        quote: >
          "Diving into the digital abyss with the Infinidat Big Data Team, crafting Python spells so potent, they make other tech solutions look like they're still stuck in the floppy disk era!"
        description: | # this will include new lines to allow paragraphs
            Engaged in the development of large-scale products designed to collect, parse, aggregate, mutate, and expose data from deployed Infinidat systems for both customer and internal use.
            This also involved the creation of relocatable <mark>Python</mark> distributions for open-source use across multiple platforms and architectures.
            Additionally, I spearheaded the code migration for multiple projects from <mark>Python 2</mark> to <mark>Python 3</mark>.

      - layout: left
        title: Check Point Software Technologies
        link: www.checkpoint.com
        sub_title: Software Engineer
        caption: Auguest 2014 - November 2017
        quote: >
          "Building the digital fortresses of the future, one line of code at a time, with the Check Point Software Technologies team, crafting solutions so secure, they make Fort Knox look like a piggy bank!"
        description: |
          Starting as a Security Analyst and progressing to Software Developer and Full Stack Developer.
          Initially, as a Security Analyst, the individual focused on network traffic analysis and identifying data patterns leveraging a lot of <mark>Regular Expressions</mark>.
          Moving on to a Software Developer role, I developed a reverse engineering solution, for auto-detection of malicious traffic using <mark>Python</mark> and <mark>C/C++</mark>, created big-data research tools for profiling network protocols, and developed automation infrastructure for web-platform services.
          As a Full Stack Developer, I designed and developed server-side API code with <mark>Java</mark>, <mark>Spring Framework</mark>, and <mark>Spring-Security</mark>, emphasizing secure sessions. I also engaged in front-end development using <mark>AngularJS</mark>, and conducted end-to-end testing with tools like <mark>Grunt</mark>, <mark>Protractor</mark>, and <mark>Selenium</mark>.
          In my final role as a Software Developer on the Telcom team, I designed and developed a secure server-side API for large Telecom corporations using a <mark>PHP5</mark>/<mark>Postgresql</mark>/<mark>Apache</mark> stack. I conducted end-to-end testing using <mark>Junit</mark> and maintained the product lifecycle with <mark>Jenkins</mark> Pipelines.
          I further developed server-side components with <mark>Python</mark> and managed deployment with <mark>Puppet</mark>, orchestrating Postgresql clustering and replication for failsafe operation.
          Additionally, they worked on product development across multiple distributed virtualized platforms, including Gaia (Chekpoint Proprietery OS), Windows Server, and RHEL.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Technion - Israel Institute of Technology
        caption: 2011 - 2016
        sub_title: Industrial Engineering - Business Information systems
        quote: >
          Established in 1912 in Haifa, Israel, is the country's oldest university and a pivotal force in the fields of science and engineering
        description: |
          During my time at The Technion I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about latest technologies used in the industry.

  - title: Contributions # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Patent
        sub_title: UPDATING A STATE OF A CLIENT DEVICE USING A LIMITED EVENT SIZE PROTOCOL
        caption: 411583-US-NP · Filed May 26, 2022411583
      
      - layout: top-middle
        title: Final Project
        sub_title: Gamification of Goal Recognition Design Problems
        caption: March 2016
        description: |
          Designing and implementing of Goal Recognition Design game to show the benefits of such algorithms. The GRD is an A.I problem set, algorithms that solve this problem set do so by reshaping the problems topology in order optimize Goal Recognition algorithms performance.
          Developed with Java, JavaFX, and Android.
      
      - layout: top-middle
        title: Voluneteering
        sub_title: SII-the standards institution of israel Central Committee Member
        caption: August 2020 - Present
        description: |
          Member of the Central Comitee for Technology and Information.
          Member of the Cyber Comitee.
          Member of Biometrics Commitee.

  - title: All work and no fun makes Jack a dull boy
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in cyber security and software engineering some of my other interests and hobbies are:
      - Mountaineering and Hiking
      - Playing classical music on the guitar
      - Bachata Dancing
      - Bouldering
      - Boxing
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
