# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Roy Belio
title: Senior Software Engineer
email: royfbelio@gmail.com
website: https://github.com/r-bit-rry

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  r-bit-rry
stackoverflow_username: "2250010"
linkedin_username: roy-belio


# About Section
about_title: \>WHOAMI
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Enthusiast senior software engineer ready to passionately tackle any challenge that can be solved with a piece of code.

  I am most skilled in: <mark>C#/Dotnet</mark> and <mark>Rust</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        link: microsoft.com
        # link_text: boringcompany.com
        sub_title: Software Developer Engineer II
        caption: May 2020 - Present
        quote: >
          "Tackling the puzzles of the 21st century by digging holes so deep we're expecting to find dinosaur fossils, and whipping up solutions so revolutionary, they make *Microsoft Defender for Enterprise* look like a rubber duck in a tech pond."
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technion - Israel Institute of Technology
        caption: 2011 - 2016
        sub_title: Industrial Engineering - Business Information systems
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Mountaineering and Hiking
      - Playing classical music on the guitar
      - Rock climbing
      - Gaming

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
